/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConnectionsRouteImport } from './routes/connections'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MapRouteImport } from './routes/map'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as StoriesRouteImport } from './routes/stories'
import { Route as TeamRouteImport } from './routes/team'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as VisionRouteImport } from './routes/vision'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AthleteIndexRouteImport } from './routes/athlete.index'
import { Route as AthleteProfileRouteImport } from './routes/athlete.profile'
import { Route as AthleteTournamentsRouteImport } from './routes/athlete.tournaments'
import { Route as AthletesIdRouteImport } from './routes/athletes.$id'
import { Route as CollegeIndexRouteImport } from './routes/college.index'
import { Route as CollegeRecordsRouteImport } from './routes/college.records'
import { Route as OrganizerIndexRouteImport } from './routes/organizer.index'
import { Route as OrganizerCreateRouteImport } from './routes/organizer.create'
import { Route as OrganizerResultsRouteImport } from './routes/organizer.results'
import { Route as TournamentsIndexRouteImport } from './routes/tournaments.index'
import { Route as TournamentsIdRouteImport } from './routes/tournaments.$id'
import { Route as VolunteerIndexRouteImport } from './routes/volunteer.index'
import { Route as OrganizerManageIdRouteImport } from './routes/organizer.manage.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectionsRoute = ConnectionsRouteImport.update({
  id: '/connections',
  path: '/connections',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesRoute = StoriesRouteImport.update({
  id: '/stories',
  path: '/stories',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const VisionRoute = VisionRouteImport.update({
  id: '/vision',
  path: '/vision',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AthleteIndexRoute = AthleteIndexRouteImport.update({
  id: '/athlete/',
  path: '/athlete/',
  getParentRoute: () => rootRouteImport,
} as any)
const AthleteProfileRoute = AthleteProfileRouteImport.update({
  id: '/athlete/profile',
  path: '/athlete/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AthleteTournamentsRoute = AthleteTournamentsRouteImport.update({
  id: '/athlete/tournaments',
  path: '/athlete/tournaments',
  getParentRoute: () => rootRouteImport,
} as any)
const AthletesIdRoute = AthletesIdRouteImport.update({
  id: '/athletes/$id',
  path: '/athletes/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CollegeIndexRoute = CollegeIndexRouteImport.update({
  id: '/college/',
  path: '/college/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollegeRecordsRoute = CollegeRecordsRouteImport.update({
  id: '/college/records',
  path: '/college/records',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizerIndexRoute = OrganizerIndexRouteImport.update({
  id: '/organizer/',
  path: '/organizer/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizerCreateRoute = OrganizerCreateRouteImport.update({
  id: '/organizer/create',
  path: '/organizer/create',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizerResultsRoute = OrganizerResultsRouteImport.update({
  id: '/organizer/results',
  path: '/organizer/results',
  getParentRoute: () => rootRouteImport,
} as any)
const TournamentsIndexRoute = TournamentsIndexRouteImport.update({
  id: '/tournaments/',
  path: '/tournaments/',
  getParentRoute: () => rootRouteImport,
} as any)
const TournamentsIdRoute = TournamentsIdRouteImport.update({
  id: '/tournaments/$id',
  path: '/tournaments/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const VolunteerIndexRoute = VolunteerIndexRouteImport.update({
  id: '/volunteer/',
  path: '/volunteer/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizerManageIdRoute = OrganizerManageIdRouteImport.update({
  id: '/organizer/manage/$id',
  path: '/organizer/manage/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/connections': typeof ConnectionsRoute
  '/contact': typeof ContactRoute
  '/demo': typeof DemoRoute
  '/discover': typeof DiscoverRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/privacy': typeof PrivacyRoute
  '/saved': typeof SavedRoute
  '/signup': typeof SignupRoute
  '/stories': typeof StoriesRoute
  '/team': typeof TeamRoute
  '/terms': typeof TermsRoute
  '/vision': typeof VisionRoute
  '/athlete/profile': typeof AthleteProfileRoute
  '/athlete/tournaments': typeof AthleteTournamentsRoute
  '/athletes/$id': typeof AthletesIdRoute
  '/college/records': typeof CollegeRecordsRoute
  '/organizer/create': typeof OrganizerCreateRoute
  '/organizer/results': typeof OrganizerResultsRoute
  '/tournaments/$id': typeof TournamentsIdRoute
  '/admin/': typeof AdminIndexRoute
  '/athlete/': typeof AthleteIndexRoute
  '/college/': typeof CollegeIndexRoute
  '/organizer/': typeof OrganizerIndexRoute
  '/tournaments/': typeof TournamentsIndexRoute
  '/volunteer/': typeof VolunteerIndexRoute
  '/organizer/manage/$id': typeof OrganizerManageIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/connections': typeof ConnectionsRoute
  '/contact': typeof ContactRoute
  '/demo': typeof DemoRoute
  '/discover': typeof DiscoverRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/privacy': typeof PrivacyRoute
  '/saved': typeof SavedRoute
  '/signup': typeof SignupRoute
  '/stories': typeof StoriesRoute
  '/team': typeof TeamRoute
  '/terms': typeof TermsRoute
  '/vision': typeof VisionRoute
  '/athlete/profile': typeof AthleteProfileRoute
  '/athlete/tournaments': typeof AthleteTournamentsRoute
  '/athletes/$id': typeof AthletesIdRoute
  '/college/records': typeof CollegeRecordsRoute
  '/organizer/create': typeof OrganizerCreateRoute
  '/organizer/results': typeof OrganizerResultsRoute
  '/tournaments/$id': typeof TournamentsIdRoute
  '/admin': typeof AdminIndexRoute
  '/athlete': typeof AthleteIndexRoute
  '/college': typeof CollegeIndexRoute
  '/organizer': typeof OrganizerIndexRoute
  '/tournaments': typeof TournamentsIndexRoute
  '/volunteer': typeof VolunteerIndexRoute
  '/organizer/manage/$id': typeof OrganizerManageIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/connections': typeof ConnectionsRoute
  '/contact': typeof ContactRoute
  '/demo': typeof DemoRoute
  '/discover': typeof DiscoverRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/privacy': typeof PrivacyRoute
  '/saved': typeof SavedRoute
  '/signup': typeof SignupRoute
  '/stories': typeof StoriesRoute
  '/team': typeof TeamRoute
  '/terms': typeof TermsRoute
  '/vision': typeof VisionRoute
  '/athlete/profile': typeof AthleteProfileRoute
  '/athlete/tournaments': typeof AthleteTournamentsRoute
  '/athletes/$id': typeof AthletesIdRoute
  '/college/records': typeof CollegeRecordsRoute
  '/organizer/create': typeof OrganizerCreateRoute
  '/organizer/results': typeof OrganizerResultsRoute
  '/tournaments/$id': typeof TournamentsIdRoute
  '/admin/': typeof AdminIndexRoute
  '/athlete/': typeof AthleteIndexRoute
  '/college/': typeof CollegeIndexRoute
  '/organizer/': typeof OrganizerIndexRoute
  '/tournaments/': typeof TournamentsIndexRoute
  '/volunteer/': typeof VolunteerIndexRoute
  '/organizer/manage/$id': typeof OrganizerManageIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/connections'
    | '/contact'
    | '/demo'
    | '/discover'
    | '/login'
    | '/map'
    | '/privacy'
    | '/saved'
    | '/signup'
    | '/stories'
    | '/team'
    | '/terms'
    | '/vision'
    | '/athlete/profile'
    | '/athlete/tournaments'
    | '/athletes/$id'
    | '/college/records'
    | '/organizer/create'
    | '/organizer/results'
    | '/tournaments/$id'
    | '/admin/'
    | '/athlete/'
    | '/college/'
    | '/organizer/'
    | '/tournaments/'
    | '/volunteer/'
    | '/organizer/manage/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/connections'
    | '/contact'
    | '/demo'
    | '/discover'
    | '/login'
    | '/map'
    | '/privacy'
    | '/saved'
    | '/signup'
    | '/stories'
    | '/team'
    | '/terms'
    | '/vision'
    | '/athlete/profile'
    | '/athlete/tournaments'
    | '/athletes/$id'
    | '/college/records'
    | '/organizer/create'
    | '/organizer/results'
    | '/tournaments/$id'
    | '/admin'
    | '/athlete'
    | '/college'
    | '/organizer'
    | '/tournaments'
    | '/volunteer'
    | '/organizer/manage/$id'
  id:
    | '__root__'
    | '/'
    | '/connections'
    | '/contact'
    | '/demo'
    | '/discover'
    | '/login'
    | '/map'
    | '/privacy'
    | '/saved'
    | '/signup'
    | '/stories'
    | '/team'
    | '/terms'
    | '/vision'
    | '/athlete/profile'
    | '/athlete/tournaments'
    | '/athletes/$id'
    | '/college/records'
    | '/organizer/create'
    | '/organizer/results'
    | '/tournaments/$id'
    | '/admin/'
    | '/athlete/'
    | '/college/'
    | '/organizer/'
    | '/tournaments/'
    | '/volunteer/'
    | '/organizer/manage/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConnectionsRoute: typeof ConnectionsRoute
  ContactRoute: typeof ContactRoute
  DemoRoute: typeof DemoRoute
  DiscoverRoute: typeof DiscoverRoute
  LoginRoute: typeof LoginRoute
  MapRoute: typeof MapRoute
  PrivacyRoute: typeof PrivacyRoute
  SavedRoute: typeof SavedRoute
  SignupRoute: typeof SignupRoute
  StoriesRoute: typeof StoriesRoute
  TeamRoute: typeof TeamRoute
  TermsRoute: typeof TermsRoute
  VisionRoute: typeof VisionRoute
  AthleteProfileRoute: typeof AthleteProfileRoute
  AthleteTournamentsRoute: typeof AthleteTournamentsRoute
  AthletesIdRoute: typeof AthletesIdRoute
  CollegeRecordsRoute: typeof CollegeRecordsRoute
  OrganizerCreateRoute: typeof OrganizerCreateRoute
  OrganizerResultsRoute: typeof OrganizerResultsRoute
  TournamentsIdRoute: typeof TournamentsIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AthleteIndexRoute: typeof AthleteIndexRoute
  CollegeIndexRoute: typeof CollegeIndexRoute
  OrganizerIndexRoute: typeof OrganizerIndexRoute
  TournamentsIndexRoute: typeof TournamentsIndexRoute
  VolunteerIndexRoute: typeof VolunteerIndexRoute
  OrganizerManageIdRoute: typeof OrganizerManageIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connections': {
      id: '/connections'
      path: '/connections'
      fullPath: '/connections'
      preLoaderRoute: typeof ConnectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories': {
      id: '/stories'
      path: '/stories'
      fullPath: '/stories'
      preLoaderRoute: typeof StoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vision': {
      id: '/vision'
      path: '/vision'
      fullPath: '/vision'
      preLoaderRoute: typeof VisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/athlete/': {
      id: '/athlete/'
      path: '/athlete'
      fullPath: '/athlete/'
      preLoaderRoute: typeof AthleteIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/athlete/profile': {
      id: '/athlete/profile'
      path: '/athlete/profile'
      fullPath: '/athlete/profile'
      preLoaderRoute: typeof AthleteProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/athlete/tournaments': {
      id: '/athlete/tournaments'
      path: '/athlete/tournaments'
      fullPath: '/athlete/tournaments'
      preLoaderRoute: typeof AthleteTournamentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/athletes/$id': {
      id: '/athletes/$id'
      path: '/athletes/$id'
      fullPath: '/athletes/$id'
      preLoaderRoute: typeof AthletesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/college/': {
      id: '/college/'
      path: '/college'
      fullPath: '/college/'
      preLoaderRoute: typeof CollegeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/college/records': {
      id: '/college/records'
      path: '/college/records'
      fullPath: '/college/records'
      preLoaderRoute: typeof CollegeRecordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizer/': {
      id: '/organizer/'
      path: '/organizer'
      fullPath: '/organizer/'
      preLoaderRoute: typeof OrganizerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizer/create': {
      id: '/organizer/create'
      path: '/organizer/create'
      fullPath: '/organizer/create'
      preLoaderRoute: typeof OrganizerCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizer/results': {
      id: '/organizer/results'
      path: '/organizer/results'
      fullPath: '/organizer/results'
      preLoaderRoute: typeof OrganizerResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournaments/': {
      id: '/tournaments/'
      path: '/tournaments'
      fullPath: '/tournaments/'
      preLoaderRoute: typeof TournamentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournaments/$id': {
      id: '/tournaments/$id'
      path: '/tournaments/$id'
      fullPath: '/tournaments/$id'
      preLoaderRoute: typeof TournamentsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/volunteer/': {
      id: '/volunteer/'
      path: '/volunteer'
      fullPath: '/volunteer/'
      preLoaderRoute: typeof VolunteerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizer/manage/$id': {
      id: '/organizer/manage/$id'
      path: '/organizer/manage/$id'
      fullPath: '/organizer/manage/$id'
      preLoaderRoute: typeof OrganizerManageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConnectionsRoute: ConnectionsRoute,
  ContactRoute: ContactRoute,
  DemoRoute: DemoRoute,
  DiscoverRoute: DiscoverRoute,
  LoginRoute: LoginRoute,
  MapRoute: MapRoute,
  PrivacyRoute: PrivacyRoute,
  SavedRoute: SavedRoute,
  SignupRoute: SignupRoute,
  StoriesRoute: StoriesRoute,
  TeamRoute: TeamRoute,
  TermsRoute: TermsRoute,
  VisionRoute: VisionRoute,
  AthleteProfileRoute: AthleteProfileRoute,
  AthleteTournamentsRoute: AthleteTournamentsRoute,
  AthletesIdRoute: AthletesIdRoute,
  CollegeRecordsRoute: CollegeRecordsRoute,
  OrganizerCreateRoute: OrganizerCreateRoute,
  OrganizerResultsRoute: OrganizerResultsRoute,
  TournamentsIdRoute: TournamentsIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  AthleteIndexRoute: AthleteIndexRoute,
  CollegeIndexRoute: CollegeIndexRoute,
  OrganizerIndexRoute: OrganizerIndexRoute,
  TournamentsIndexRoute: TournamentsIndexRoute,
  VolunteerIndexRoute: VolunteerIndexRoute,
  OrganizerManageIdRoute: OrganizerManageIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
