/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AthletesRouteImport } from './routes/athletes'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as CitiesRouteImport } from './routes/cities'
import { Route as ConnectionsRouteImport } from './routes/connections'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as FeedbackRouteImport } from './routes/feedback'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as InstitutionsRouteImport } from './routes/institutions'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MapRouteImport } from './routes/map'
import { Route as OrganizersRouteImport } from './routes/organizers'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SportsRouteImport } from './routes/sports'
import { Route as StoriesRouteImport } from './routes/stories'
import { Route as TeamRouteImport } from './routes/team'
import { Route as TeamsRouteImport } from './routes/teams'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as VerificationRouteImport } from './routes/verification'
import { Route as VisionRouteImport } from './routes/vision'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AthleteIndexRouteImport } from './routes/athlete.index'
import { Route as AthleteProfileRouteImport } from './routes/athlete.profile'
import { Route as AthleteTournamentsRouteImport } from './routes/athlete.tournaments'
import { Route as AthletesIdRouteImport } from './routes/athletes.$id'
import { Route as CitiesIndoreRouteImport } from './routes/cities.indore'
import { Route as CollegeIndexRouteImport } from './routes/college.index'
import { Route as CollegeRecordsRouteImport } from './routes/college.records'
import { Route as OrganizerIndexRouteImport } from './routes/organizer.index'
import { Route as OrganizerCreateRouteImport } from './routes/organizer.create'
import { Route as OrganizerResultsRouteImport } from './routes/organizer.results'
import { Route as SportsSportRouteImport } from './routes/sports.$sport'
import { Route as TeamMemberRouteImport } from './routes/team.$member'
import { Route as TournamentsIndexRouteImport } from './routes/tournaments.index'
import { Route as TournamentsIdRouteImport } from './routes/tournaments.$id'
import { Route as TournamentsCreateRouteImport } from './routes/tournaments.create'
import { Route as VolunteerIndexRouteImport } from './routes/volunteer.index'
import { Route as VolunteerDeskRouteImport } from './routes/volunteer.desk'
import { Route as OrganizerManageIdRouteImport } from './routes/organizer.manage.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AthletesRoute = AthletesRouteImport.update({
  id: '/athletes',
  path: '/athletes',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const CitiesRoute = CitiesRouteImport.update({
  id: '/cities',
  path: '/cities',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectionsRoute = ConnectionsRouteImport.update({
  id: '/connections',
  path: '/connections',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackRoute = FeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const InstitutionsRoute = InstitutionsRouteImport.update({
  id: '/institutions',
  path: '/institutions',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizersRoute = OrganizersRouteImport.update({
  id: '/organizers',
  path: '/organizers',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SportsRoute = SportsRouteImport.update({
  id: '/sports',
  path: '/sports',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesRoute = StoriesRouteImport.update({
  id: '/stories',
  path: '/stories',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsRoute = TeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const VerificationRoute = VerificationRouteImport.update({
  id: '/verification',
  path: '/verification',
  getParentRoute: () => rootRouteImport,
} as any)
const VisionRoute = VisionRouteImport.update({
  id: '/vision',
  path: '/vision',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AthleteIndexRoute = AthleteIndexRouteImport.update({
  id: '/athlete/',
  path: '/athlete/',
  getParentRoute: () => rootRouteImport,
} as any)
const AthleteProfileRoute = AthleteProfileRouteImport.update({
  id: '/athlete/profile',
  path: '/athlete/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AthleteTournamentsRoute = AthleteTournamentsRouteImport.update({
  id: '/athlete/tournaments',
  path: '/athlete/tournaments',
  getParentRoute: () => rootRouteImport,
} as any)
const AthletesIdRoute = AthletesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AthletesRoute,
} as any)
const CitiesIndoreRoute = CitiesIndoreRouteImport.update({
  id: '/indore',
  path: '/indore',
  getParentRoute: () => CitiesRoute,
} as any)
const CollegeIndexRoute = CollegeIndexRouteImport.update({
  id: '/college/',
  path: '/college/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollegeRecordsRoute = CollegeRecordsRouteImport.update({
  id: '/college/records',
  path: '/college/records',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizerIndexRoute = OrganizerIndexRouteImport.update({
  id: '/organizer/',
  path: '/organizer/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizerCreateRoute = OrganizerCreateRouteImport.update({
  id: '/organizer/create',
  path: '/organizer/create',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizerResultsRoute = OrganizerResultsRouteImport.update({
  id: '/organizer/results',
  path: '/organizer/results',
  getParentRoute: () => rootRouteImport,
} as any)
const SportsSportRoute = SportsSportRouteImport.update({
  id: '/$sport',
  path: '/$sport',
  getParentRoute: () => SportsRoute,
} as any)
const TeamMemberRoute = TeamMemberRouteImport.update({
  id: '/$member',
  path: '/$member',
  getParentRoute: () => TeamRoute,
} as any)
const TournamentsIndexRoute = TournamentsIndexRouteImport.update({
  id: '/tournaments/',
  path: '/tournaments/',
  getParentRoute: () => rootRouteImport,
} as any)
const TournamentsIdRoute = TournamentsIdRouteImport.update({
  id: '/tournaments/$id',
  path: '/tournaments/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const TournamentsCreateRoute = TournamentsCreateRouteImport.update({
  id: '/tournaments/create',
  path: '/tournaments/create',
  getParentRoute: () => rootRouteImport,
} as any)
const VolunteerIndexRoute = VolunteerIndexRouteImport.update({
  id: '/volunteer/',
  path: '/volunteer/',
  getParentRoute: () => rootRouteImport,
} as any)
const VolunteerDeskRoute = VolunteerDeskRouteImport.update({
  id: '/volunteer/desk',
  path: '/volunteer/desk',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizerManageIdRoute = OrganizerManageIdRouteImport.update({
  id: '/organizer/manage/$id',
  path: '/organizer/manage/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/athletes': typeof AthletesRouteWithChildren
  '/careers': typeof CareersRoute
  '/cities': typeof CitiesRouteWithChildren
  '/connections': typeof ConnectionsRoute
  '/contact': typeof ContactRoute
  '/demo': typeof DemoRoute
  '/discover': typeof DiscoverRoute
  '/explore': typeof ExploreRoute
  '/feedback': typeof FeedbackRoute
  '/how-it-works': typeof HowItWorksRoute
  '/institutions': typeof InstitutionsRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/organizers': typeof OrganizersRoute
  '/privacy': typeof PrivacyRoute
  '/saved': typeof SavedRoute
  '/shop': typeof ShopRoute
  '/signup': typeof SignupRoute
  '/sports': typeof SportsRouteWithChildren
  '/stories': typeof StoriesRoute
  '/team': typeof TeamRouteWithChildren
  '/teams': typeof TeamsRoute
  '/terms': typeof TermsRoute
  '/verification': typeof VerificationRoute
  '/vision': typeof VisionRoute
  '/athlete/profile': typeof AthleteProfileRoute
  '/athlete/tournaments': typeof AthleteTournamentsRoute
  '/athletes/$id': typeof AthletesIdRoute
  '/cities/indore': typeof CitiesIndoreRoute
  '/college/records': typeof CollegeRecordsRoute
  '/organizer/create': typeof OrganizerCreateRoute
  '/organizer/results': typeof OrganizerResultsRoute
  '/sports/$sport': typeof SportsSportRoute
  '/team/$member': typeof TeamMemberRoute
  '/tournaments/$id': typeof TournamentsIdRoute
  '/tournaments/create': typeof TournamentsCreateRoute
  '/volunteer/desk': typeof VolunteerDeskRoute
  '/admin/': typeof AdminIndexRoute
  '/athlete/': typeof AthleteIndexRoute
  '/college/': typeof CollegeIndexRoute
  '/organizer/': typeof OrganizerIndexRoute
  '/tournaments/': typeof TournamentsIndexRoute
  '/volunteer/': typeof VolunteerIndexRoute
  '/organizer/manage/$id': typeof OrganizerManageIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/athletes': typeof AthletesRouteWithChildren
  '/careers': typeof CareersRoute
  '/cities': typeof CitiesRouteWithChildren
  '/connections': typeof ConnectionsRoute
  '/contact': typeof ContactRoute
  '/demo': typeof DemoRoute
  '/discover': typeof DiscoverRoute
  '/explore': typeof ExploreRoute
  '/feedback': typeof FeedbackRoute
  '/how-it-works': typeof HowItWorksRoute
  '/institutions': typeof InstitutionsRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/organizers': typeof OrganizersRoute
  '/privacy': typeof PrivacyRoute
  '/saved': typeof SavedRoute
  '/shop': typeof ShopRoute
  '/signup': typeof SignupRoute
  '/sports': typeof SportsRouteWithChildren
  '/stories': typeof StoriesRoute
  '/team': typeof TeamRouteWithChildren
  '/teams': typeof TeamsRoute
  '/terms': typeof TermsRoute
  '/verification': typeof VerificationRoute
  '/vision': typeof VisionRoute
  '/athlete/profile': typeof AthleteProfileRoute
  '/athlete/tournaments': typeof AthleteTournamentsRoute
  '/athletes/$id': typeof AthletesIdRoute
  '/cities/indore': typeof CitiesIndoreRoute
  '/college/records': typeof CollegeRecordsRoute
  '/organizer/create': typeof OrganizerCreateRoute
  '/organizer/results': typeof OrganizerResultsRoute
  '/sports/$sport': typeof SportsSportRoute
  '/team/$member': typeof TeamMemberRoute
  '/tournaments/$id': typeof TournamentsIdRoute
  '/tournaments/create': typeof TournamentsCreateRoute
  '/volunteer/desk': typeof VolunteerDeskRoute
  '/admin': typeof AdminIndexRoute
  '/athlete': typeof AthleteIndexRoute
  '/college': typeof CollegeIndexRoute
  '/organizer': typeof OrganizerIndexRoute
  '/tournaments': typeof TournamentsIndexRoute
  '/volunteer': typeof VolunteerIndexRoute
  '/organizer/manage/$id': typeof OrganizerManageIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/athletes': typeof AthletesRouteWithChildren
  '/careers': typeof CareersRoute
  '/cities': typeof CitiesRouteWithChildren
  '/connections': typeof ConnectionsRoute
  '/contact': typeof ContactRoute
  '/demo': typeof DemoRoute
  '/discover': typeof DiscoverRoute
  '/explore': typeof ExploreRoute
  '/feedback': typeof FeedbackRoute
  '/how-it-works': typeof HowItWorksRoute
  '/institutions': typeof InstitutionsRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/organizers': typeof OrganizersRoute
  '/privacy': typeof PrivacyRoute
  '/saved': typeof SavedRoute
  '/shop': typeof ShopRoute
  '/signup': typeof SignupRoute
  '/sports': typeof SportsRouteWithChildren
  '/stories': typeof StoriesRoute
  '/team': typeof TeamRouteWithChildren
  '/teams': typeof TeamsRoute
  '/terms': typeof TermsRoute
  '/verification': typeof VerificationRoute
  '/vision': typeof VisionRoute
  '/athlete/profile': typeof AthleteProfileRoute
  '/athlete/tournaments': typeof AthleteTournamentsRoute
  '/athletes/$id': typeof AthletesIdRoute
  '/cities/indore': typeof CitiesIndoreRoute
  '/college/records': typeof CollegeRecordsRoute
  '/organizer/create': typeof OrganizerCreateRoute
  '/organizer/results': typeof OrganizerResultsRoute
  '/sports/$sport': typeof SportsSportRoute
  '/team/$member': typeof TeamMemberRoute
  '/tournaments/$id': typeof TournamentsIdRoute
  '/tournaments/create': typeof TournamentsCreateRoute
  '/volunteer/desk': typeof VolunteerDeskRoute
  '/admin/': typeof AdminIndexRoute
  '/athlete/': typeof AthleteIndexRoute
  '/college/': typeof CollegeIndexRoute
  '/organizer/': typeof OrganizerIndexRoute
  '/tournaments/': typeof TournamentsIndexRoute
  '/volunteer/': typeof VolunteerIndexRoute
  '/organizer/manage/$id': typeof OrganizerManageIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/athletes'
    | '/careers'
    | '/cities'
    | '/connections'
    | '/contact'
    | '/demo'
    | '/discover'
    | '/explore'
    | '/feedback'
    | '/how-it-works'
    | '/institutions'
    | '/login'
    | '/map'
    | '/organizers'
    | '/privacy'
    | '/saved'
    | '/shop'
    | '/signup'
    | '/sports'
    | '/stories'
    | '/team'
    | '/teams'
    | '/terms'
    | '/verification'
    | '/vision'
    | '/athlete/profile'
    | '/athlete/tournaments'
    | '/athletes/$id'
    | '/cities/indore'
    | '/college/records'
    | '/organizer/create'
    | '/organizer/results'
    | '/sports/$sport'
    | '/team/$member'
    | '/tournaments/$id'
    | '/tournaments/create'
    | '/volunteer/desk'
    | '/admin/'
    | '/athlete/'
    | '/college/'
    | '/organizer/'
    | '/tournaments/'
    | '/volunteer/'
    | '/organizer/manage/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/athletes'
    | '/careers'
    | '/cities'
    | '/connections'
    | '/contact'
    | '/demo'
    | '/discover'
    | '/explore'
    | '/feedback'
    | '/how-it-works'
    | '/institutions'
    | '/login'
    | '/map'
    | '/organizers'
    | '/privacy'
    | '/saved'
    | '/shop'
    | '/signup'
    | '/sports'
    | '/stories'
    | '/team'
    | '/teams'
    | '/terms'
    | '/verification'
    | '/vision'
    | '/athlete/profile'
    | '/athlete/tournaments'
    | '/athletes/$id'
    | '/cities/indore'
    | '/college/records'
    | '/organizer/create'
    | '/organizer/results'
    | '/sports/$sport'
    | '/team/$member'
    | '/tournaments/$id'
    | '/tournaments/create'
    | '/volunteer/desk'
    | '/admin'
    | '/athlete'
    | '/college'
    | '/organizer'
    | '/tournaments'
    | '/volunteer'
    | '/organizer/manage/$id'
  id:
    | '__root__'
    | '/'
    | '/athletes'
    | '/careers'
    | '/cities'
    | '/connections'
    | '/contact'
    | '/demo'
    | '/discover'
    | '/explore'
    | '/feedback'
    | '/how-it-works'
    | '/institutions'
    | '/login'
    | '/map'
    | '/organizers'
    | '/privacy'
    | '/saved'
    | '/shop'
    | '/signup'
    | '/sports'
    | '/stories'
    | '/team'
    | '/teams'
    | '/terms'
    | '/verification'
    | '/vision'
    | '/athlete/profile'
    | '/athlete/tournaments'
    | '/athletes/$id'
    | '/cities/indore'
    | '/college/records'
    | '/organizer/create'
    | '/organizer/results'
    | '/sports/$sport'
    | '/team/$member'
    | '/tournaments/$id'
    | '/tournaments/create'
    | '/volunteer/desk'
    | '/admin/'
    | '/athlete/'
    | '/college/'
    | '/organizer/'
    | '/tournaments/'
    | '/volunteer/'
    | '/organizer/manage/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AthletesRoute: typeof AthletesRouteWithChildren
  CareersRoute: typeof CareersRoute
  CitiesRoute: typeof CitiesRouteWithChildren
  ConnectionsRoute: typeof ConnectionsRoute
  ContactRoute: typeof ContactRoute
  DemoRoute: typeof DemoRoute
  DiscoverRoute: typeof DiscoverRoute
  ExploreRoute: typeof ExploreRoute
  FeedbackRoute: typeof FeedbackRoute
  HowItWorksRoute: typeof HowItWorksRoute
  InstitutionsRoute: typeof InstitutionsRoute
  LoginRoute: typeof LoginRoute
  MapRoute: typeof MapRoute
  OrganizersRoute: typeof OrganizersRoute
  PrivacyRoute: typeof PrivacyRoute
  SavedRoute: typeof SavedRoute
  ShopRoute: typeof ShopRoute
  SignupRoute: typeof SignupRoute
  SportsRoute: typeof SportsRouteWithChildren
  StoriesRoute: typeof StoriesRoute
  TeamRoute: typeof TeamRouteWithChildren
  TeamsRoute: typeof TeamsRoute
  TermsRoute: typeof TermsRoute
  VerificationRoute: typeof VerificationRoute
  VisionRoute: typeof VisionRoute
  AthleteProfileRoute: typeof AthleteProfileRoute
  AthleteTournamentsRoute: typeof AthleteTournamentsRoute
  CollegeRecordsRoute: typeof CollegeRecordsRoute
  OrganizerCreateRoute: typeof OrganizerCreateRoute
  OrganizerResultsRoute: typeof OrganizerResultsRoute
  TournamentsIdRoute: typeof TournamentsIdRoute
  TournamentsCreateRoute: typeof TournamentsCreateRoute
  VolunteerDeskRoute: typeof VolunteerDeskRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AthleteIndexRoute: typeof AthleteIndexRoute
  CollegeIndexRoute: typeof CollegeIndexRoute
  OrganizerIndexRoute: typeof OrganizerIndexRoute
  TournamentsIndexRoute: typeof TournamentsIndexRoute
  VolunteerIndexRoute: typeof VolunteerIndexRoute
  OrganizerManageIdRoute: typeof OrganizerManageIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/athletes': {
      id: '/athletes'
      path: '/athletes'
      fullPath: '/athletes'
      preLoaderRoute: typeof AthletesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cities': {
      id: '/cities'
      path: '/cities'
      fullPath: '/cities'
      preLoaderRoute: typeof CitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connections': {
      id: '/connections'
      path: '/connections'
      fullPath: '/connections'
      preLoaderRoute: typeof ConnectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/institutions': {
      id: '/institutions'
      path: '/institutions'
      fullPath: '/institutions'
      preLoaderRoute: typeof InstitutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizers': {
      id: '/organizers'
      path: '/organizers'
      fullPath: '/organizers'
      preLoaderRoute: typeof OrganizersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sports': {
      id: '/sports'
      path: '/sports'
      fullPath: '/sports'
      preLoaderRoute: typeof SportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories': {
      id: '/stories'
      path: '/stories'
      fullPath: '/stories'
      preLoaderRoute: typeof StoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams': {
      id: '/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof TeamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verification': {
      id: '/verification'
      path: '/verification'
      fullPath: '/verification'
      preLoaderRoute: typeof VerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vision': {
      id: '/vision'
      path: '/vision'
      fullPath: '/vision'
      preLoaderRoute: typeof VisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/athlete/': {
      id: '/athlete/'
      path: '/athlete'
      fullPath: '/athlete/'
      preLoaderRoute: typeof AthleteIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/athlete/profile': {
      id: '/athlete/profile'
      path: '/athlete/profile'
      fullPath: '/athlete/profile'
      preLoaderRoute: typeof AthleteProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/athlete/tournaments': {
      id: '/athlete/tournaments'
      path: '/athlete/tournaments'
      fullPath: '/athlete/tournaments'
      preLoaderRoute: typeof AthleteTournamentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/athletes/$id': {
      id: '/athletes/$id'
      path: '/$id'
      fullPath: '/athletes/$id'
      preLoaderRoute: typeof AthletesIdRouteImport
      parentRoute: typeof AthletesRoute
    }
    '/cities/indore': {
      id: '/cities/indore'
      path: '/indore'
      fullPath: '/cities/indore'
      preLoaderRoute: typeof CitiesIndoreRouteImport
      parentRoute: typeof CitiesRoute
    }
    '/college/': {
      id: '/college/'
      path: '/college'
      fullPath: '/college/'
      preLoaderRoute: typeof CollegeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/college/records': {
      id: '/college/records'
      path: '/college/records'
      fullPath: '/college/records'
      preLoaderRoute: typeof CollegeRecordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizer/': {
      id: '/organizer/'
      path: '/organizer'
      fullPath: '/organizer/'
      preLoaderRoute: typeof OrganizerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizer/create': {
      id: '/organizer/create'
      path: '/organizer/create'
      fullPath: '/organizer/create'
      preLoaderRoute: typeof OrganizerCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizer/results': {
      id: '/organizer/results'
      path: '/organizer/results'
      fullPath: '/organizer/results'
      preLoaderRoute: typeof OrganizerResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sports/$sport': {
      id: '/sports/$sport'
      path: '/$sport'
      fullPath: '/sports/$sport'
      preLoaderRoute: typeof SportsSportRouteImport
      parentRoute: typeof SportsRoute
    }
    '/team/$member': {
      id: '/team/$member'
      path: '/$member'
      fullPath: '/team/$member'
      preLoaderRoute: typeof TeamMemberRouteImport
      parentRoute: typeof TeamRoute
    }
    '/tournaments/': {
      id: '/tournaments/'
      path: '/tournaments'
      fullPath: '/tournaments/'
      preLoaderRoute: typeof TournamentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournaments/$id': {
      id: '/tournaments/$id'
      path: '/tournaments/$id'
      fullPath: '/tournaments/$id'
      preLoaderRoute: typeof TournamentsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournaments/create': {
      id: '/tournaments/create'
      path: '/tournaments/create'
      fullPath: '/tournaments/create'
      preLoaderRoute: typeof TournamentsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/volunteer/': {
      id: '/volunteer/'
      path: '/volunteer'
      fullPath: '/volunteer/'
      preLoaderRoute: typeof VolunteerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/volunteer/desk': {
      id: '/volunteer/desk'
      path: '/volunteer/desk'
      fullPath: '/volunteer/desk'
      preLoaderRoute: typeof VolunteerDeskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizer/manage/$id': {
      id: '/organizer/manage/$id'
      path: '/organizer/manage/$id'
      fullPath: '/organizer/manage/$id'
      preLoaderRoute: typeof OrganizerManageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AthletesRouteChildren {
  AthletesIdRoute: typeof AthletesIdRoute
}

const AthletesRouteChildren: AthletesRouteChildren = {
  AthletesIdRoute: AthletesIdRoute,
}

const AthletesRouteWithChildren = AthletesRoute._addFileChildren(
  AthletesRouteChildren,
)

interface CitiesRouteChildren {
  CitiesIndoreRoute: typeof CitiesIndoreRoute
}

const CitiesRouteChildren: CitiesRouteChildren = {
  CitiesIndoreRoute: CitiesIndoreRoute,
}

const CitiesRouteWithChildren =
  CitiesRoute._addFileChildren(CitiesRouteChildren)

interface SportsRouteChildren {
  SportsSportRoute: typeof SportsSportRoute
}

const SportsRouteChildren: SportsRouteChildren = {
  SportsSportRoute: SportsSportRoute,
}

const SportsRouteWithChildren =
  SportsRoute._addFileChildren(SportsRouteChildren)

interface TeamRouteChildren {
  TeamMemberRoute: typeof TeamMemberRoute
}

const TeamRouteChildren: TeamRouteChildren = {
  TeamMemberRoute: TeamMemberRoute,
}

const TeamRouteWithChildren = TeamRoute._addFileChildren(TeamRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AthletesRoute: AthletesRouteWithChildren,
  CareersRoute: CareersRoute,
  CitiesRoute: CitiesRouteWithChildren,
  ConnectionsRoute: ConnectionsRoute,
  ContactRoute: ContactRoute,
  DemoRoute: DemoRoute,
  DiscoverRoute: DiscoverRoute,
  ExploreRoute: ExploreRoute,
  FeedbackRoute: FeedbackRoute,
  HowItWorksRoute: HowItWorksRoute,
  InstitutionsRoute: InstitutionsRoute,
  LoginRoute: LoginRoute,
  MapRoute: MapRoute,
  OrganizersRoute: OrganizersRoute,
  PrivacyRoute: PrivacyRoute,
  SavedRoute: SavedRoute,
  ShopRoute: ShopRoute,
  SignupRoute: SignupRoute,
  SportsRoute: SportsRouteWithChildren,
  StoriesRoute: StoriesRoute,
  TeamRoute: TeamRouteWithChildren,
  TeamsRoute: TeamsRoute,
  TermsRoute: TermsRoute,
  VerificationRoute: VerificationRoute,
  VisionRoute: VisionRoute,
  AthleteProfileRoute: AthleteProfileRoute,
  AthleteTournamentsRoute: AthleteTournamentsRoute,
  CollegeRecordsRoute: CollegeRecordsRoute,
  OrganizerCreateRoute: OrganizerCreateRoute,
  OrganizerResultsRoute: OrganizerResultsRoute,
  TournamentsIdRoute: TournamentsIdRoute,
  TournamentsCreateRoute: TournamentsCreateRoute,
  VolunteerDeskRoute: VolunteerDeskRoute,
  AdminIndexRoute: AdminIndexRoute,
  AthleteIndexRoute: AthleteIndexRoute,
  CollegeIndexRoute: CollegeIndexRoute,
  OrganizerIndexRoute: OrganizerIndexRoute,
  TournamentsIndexRoute: TournamentsIndexRoute,
  VolunteerIndexRoute: VolunteerIndexRoute,
  OrganizerManageIdRoute: OrganizerManageIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
